	#Cargo.o
		g++ -c src/Cargo.cpp -I include/ -o build/Cargo.o

	#Cliente.o
		g++ -c src/Cliente.cpp -I include/ -o build/Cliente.o

	#Departamento.o
		g++ -c src/Departamento.cpp -I include/ -o build/Departamento.o

	#Empresa.o
		g++ -c src/Empresa.cpp -I include/ -o build/Empresa.o
	
	#Estoque.o
		g++ -c src/Estoque.cpp -I include/ -o build/Estoque.o

	#Fornecedor.o
		g++ -c src/Fornecedor.cpp -I include/ -o build/Fornecedor.o
	
	#Funcionarios.o
		g++ -c src/Funcionarios.cpp -I include/ -o build/Funcionarios.o
	
	#Lote.o
		g++ -c src/Lote.cpp -I include/ -o build/Lote.o

	#MateriaPrima.o
		g++ -c src/MateriaPrima.cpp -I include/ -o build/MateriaPrima.o
	
	#Orcamento.o
		g++ -c src/Orcamento.cpp -I include/ -o build/Orcamento.o
	
	#Pessoa.o
		g++ -c src/Pessoa.cpp -I include/ -o build/Pessoa.o
	
	#Produto.o
		g++ -c src/Produto.cpp -I include/ -o build/Produto.o

	#Proposta.o
		g++ -c src/Proposta.cpp -I include/ -o build/Proposta.o
	
	#Rota.o
		g++ -c src/Rota.cpp -I include/ -o build/Rota.o

	#Usuario.o
		g++ -c src/Usuario.cpp -I include/ -o build/Usuario.o
	
	#Validacao.o
		g++ -c src/Validacao.cpp -I include/ -o build/Validacao.o
	
	#Veiculo.o
		g++ -c src/Veiculo.cpp -I include/ -o build/Veiculo.o
	
	#Venda.o
		g++ -c src/Venda.cpp -I include/ -o build/Venda.o